### ISSUE TITLE
Activity 6.5.6: integer inputs -> integer Vandermonde matrix -> potential type issues with augment

### ISSUE THREAD

**Issue by rhinopotamus** [davidaustinm/ula#4]
In [Activity 6.5.6](https://davidaustinm.github.io/ula/sec-least-squares.html#activity-86), if students attempt to solve the normal equation by augmenting `A.T*A` with `A.T*ice`, a subtle typing issue occurs: since the vector `month` is a vector of integers, the vandermonde matrix (and its transpose) is a matrix over ZZ. However, `A.T*ice` is a vector over RDF, and so `(A.T*A).augment(A.T*ice)` fails because Sage doesn't want to coerce that matrix out of ZZ.

The hacky solution is `(A.T*A).change_ring(RDF).augment(A.T*ice)`, which leads me to the following suggestion: if the vector `month` is stored in such a way that Sage thinks of it as a vector over RDF rather than a vector over ZZ, then the Vandermonde matrix will also be a matrix over RDF, and this avoids the coercion issue. So I think if the vector of months is stored in [sea_ice.csv](https://raw.githubusercontent.com/davidaustinm/ula_modules/master/data/sea_ice.csv) as [1.0 2.0 3.0...] rather than [1 2 3...], this would avoid the coercion issue with augment.

Certainly the *real* answer is to avoid the normal equation altogether by using the QR-factorization to compute `R.inverse()*Q.T*ice`, because it's numerically better-behaved (but for reasons of scheduling I'm avoiding QR-factorization this semester). I wonder if changing the vector of months in this way causes the QR-factorization to behave in a less desirable way, though, in which case you should please feel free to ignore this issue.

**Comment by davidaustinm** [comment]
Thanks for letting me know about this issue.  I hadn't thought of that possibility!  I updated the file sea_ice.csv as you suggested, and it appears that everything is working.  Please let me know whether that takes care of the issue or it breaks something else.

**Comment by rhinopotamus** [comment]
Thanks for the quick fix! 

My results look pretty good:
```
A = vandermonde(month, 5)
xhat=(((A.T*A).augment(A.T*ice)).rref()) * vector([0,0,0,0,0,0,1])
plot_model(xhat, data)
```
![deg-5-fit](https://user-images.githubusercontent.com/8881658/143066060-a30cfcb0-3f62-43ac-8750-4e7297883242.png)

The only thing that anyone might be sad about is that, before, the QR matrices ended up being nice things over a symbolic ring and now they live over RDF, but I don't think it really affects the performance of the solution `R.inverse()* Q.T*ice`. (I checked this solution versus my solution by the normal equations for the fifth-degree fit and they only differ by things on the order of 10^-10.)

**Comment by davidaustinm** [comment]
Looks good.  That's what I found as well.  I'm not too worried about what the QR factors look like.  By this stage, my students aren't really looking at them anymore and instead just use them as you write above.  

Thanks again.  I appreciate the care you're taking with the activities and exercises.

**Comment by rhinopotamus** [comment]
Thank you for a lovely book! I'm keeping a punchlist of various small typo fixes that I plan to work on over winter break.

**Comment by davidaustinm** [comment]
That would be great!  I know there's a bunch of improvements to make, but there wasn't enough summer last year to make the kind of progress I'd hoped for.
