### ISSUE TITLE
Activity 7.2.5 part (f) Sage error, plus re-sizing window

### ISSUE THREAD

**Issue by mattboelkins** [davidaustinm/ula#7]
At https://understandinglinearalgebra.org/sec-quadratic-forms.html#li-5156, if you execute the Sage cell, you get an error because the variable y is undefined.

x, y = var('x,y') fixes the undefined variable issue

but then the plot also isn't very informative in the given window [-2,2]x[-2,2] (Sage scales it in odd ways so the plot is "vertially narrow").  I instead suggest 

x, y = var('x,y')
plot3d(2*x^3 - 6*x*y + 3*y^2, (x, 0.75,1.25), (y,0.75,1.25))

**Comment by davidaustinm** [comment]
Fixed.
